### ISSUE TITLE
Running PiWind via MDK

### ISSUE THREAD

**Issue by sr-murthy** [OasisLMF/OasisPiWind#21]
Continuation of https://github.com/OasisLMF/OasisLMF/issues/94

**Comment by sr-murthy** [comment]
@rkbanagar you asked
>I am trying to run the Oasis model for a dummy data outside the Pi city domain.
>
>Can I create a areaperil_dict.csv lying outside the Pi city or the global domain is hard coded?
>
>Can the Global boundary(-0.9176515, 52.7339933, -0.8569864, 52.7946584) for PIwind be customized?

Firstly, the keys data, including the peril area and vuln. data, and the model data, are all tied to the PiWind model, which is based on the town of Melton Mowbray (52.7661°N, 0.8860°W). The peril areas dict file defines 100 areas centred around the town

https://github.com/OasisLMF/OasisPiWind/blob/master/keys_data/PiWind/area_peril_dict2.csv. The PiWind lookup is a built-in lookup provided by the MDK package, and is controlled via the lookup config. file (`lookup.json`).

We cannot change these areas without changing the model. What you can do instead is to fork the PiWind repository, and make your changes to the peril areas dict file, but then that would require you to generate a new Rtree file index for the peril areas, and also other changes to the model data and other assets.

**Comment by sr-murthy** [comment]
The "global boundary" in this context refers to the boundary of the convex hull of all the peril areas defined in the PiWind model. These areas are centred around (52.7661°N, 0.8860°W). It is tied to the model, so it can't really be changed.

**Comment by sr-murthy** [comment]
If you have your own model you want to run via Oasis then you can do that first by creating your own model repository. Please contact support@oasislmf.org.

**Comment by rkbanagar** [comment]
I am very thankful to your enthusiasm to respond to the query.
I will do the needful.

Kind Regards

Ramesh
