### ISSUE TITLE
Binder fails to run `oasislmf`

### ISSUE THREAD

**Issue by hsteptoe** [OasisLMF/OasisPiWind#32]
`running_piwind.ipynb` in Binder fails to run the line:

``` shell
oasislmf model run -C oasislmf.json -r /tmp/analysis_test
```

returning:

```
Starting model run (@ 2019-Feb-21 08:42:51)

Creating Oasis files directory /tmp/analysis_test/input/csv
source_exposure_file_path could not be found in the command args or config file (/home/jovyan/oasislmf.json) but is required
```

This results in the visulisation in the next code block failing with 

```python
IOError: File /tmp/analysis_test/output/gul_S1_leccalc_full_uncertainty_aep.csv does not exist
```

**Comment by sr-murthy** [comment]
So this message
```
source_exposure_file_path could not be found in the command args or config file (/home/jovyan/oasislmf.json) but is require
```
indicates that the PiWind MDK config. file you're using `oasislmf.json` doesn't specify the path of the source exposure file, which is one of the required files for running a model (or even just to generate the Oasis input files).

**Comment by hsteptoe** [comment]
Yes, but if you make this available to run via Binder (which is a great idea), this should be accounted for in the Binder build.  Why is it looking in `/home/jovyan/oasislmf.json` which seems specific to user `jovyan`.  Can this be put into the Binder build?

**Comment by mpinkerton-oasis** [comment]
The binder set up may have got out of sync with recent MDK updates. We will take a look. As you say, the binder build should be set up to work as is.

**Comment by DanielTrisura** [comment]
After running into this problem I've discovered that multiple places in oasislmf.json had "source_exposures_file_path": "tests/data/SourceLocPiWind10.csv" vs
"source_exposure_file_path": "tests/data/SourceLocPiWind10.csv"

After correcting all of these I get to a new error!

> Getting model info and lookup
> STARTED: oasislmf.model_preparation.lookup.__init__
> STARTED: oasislmf.model_preparation.lookup.__init__
> COMPLETED: oasislmf.model_preparation.lookup.__init__ in 0.0s
> STARTED: oasislmf.model_preparation.lookup.__init__
> STARTED: oasislmf.model_preparation.lookup.__init__
> COMPLETED: oasislmf.model_preparation.lookup.__init__ in 0.0s
> COMPLETED: oasislmf.model_preparation.lookup.__init__ in 0.0s
> STARTED: oasislmf.model_preparation.lookup.__init__
> STARTED: oasislmf.model_preparation.lookup.__init__
> COMPLETED: oasislmf.model_preparation.lookup.__init__ in 0.0s
> STARTED: oasislmf.model_preparation.lookup.get_vulnerabilities
> Traceback (most recent call last):
>   File "/home/daniel/.local/bin/oasislmf", line 7, in <module>
>     sys.exit(RootCmd().run())
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/cli/root.py", line 39, in run
>     return super(OasisBaseCommand, self).run(args=args)
>   File "/home/daniel/.local/lib/python2.7/site-packages/argparsetree/cmd.py", line 159, in run
>     return cmd_cls(sub_command_name).run(args)
>   File "/home/daniel/.local/lib/python2.7/site-packages/argparsetree/cmd.py", line 159, in run
>     return cmd_cls(sub_command_name).run(args)
>   File "/home/daniel/.local/lib/python2.7/site-packages/argparsetree/cmd.py", line 161, in run
>     return self.action(args) or 0
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/cli/model.py", line 1051, in action
>     gen_oasis_files_cmd.action(args)
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/cli/model.py", line 651, in action
>     lookup_package_path=lookup_package_fp
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/model_preparation/lookup.py", line 421, in create
>     loc_id_col=loc_id_col
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/utils/log.py", line 114, in wrapper
>     result = func(*args, **kwargs)
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/model_preparation/lookup.py", line 740, in __init__
>     loc_id_col=self.loc_id_col
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/utils/log.py", line 114, in wrapper
>     result = func(*args, **kwargs)
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/model_preparation/lookup.py", line 1001, in __init__
>     self.col_dtypes, self.key_cols, self.vuln_id_col, self.vulnerabilities = self.get_vulnerabilities(vulnerabilities=vulnerabilities)
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/utils/log.py", line 114, in wrapper
>     result = func(*args, **kwargs)
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/model_preparation/lookup.py", line 1089, in get_vulnerabilities
>     sort_ascending=sort_ascending
>   File "/home/daniel/.local/lib/python2.7/site-packages/oasislmf/utils/data.py", line 89, in get_dataframe
>     df[col] = df[col].astype(dtype) if dtype != int else df[col].astype(object)
>   File "/home/daniel/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 5691, in astype
>     **kwargs)
>   File "/home/daniel/.local/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 531, in astype
>     return self.apply('astype', dtype=dtype, **kwargs)
>   File "/home/daniel/.local/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 395, in apply
>     applied = getattr(b, f)(**kwargs)
>   File "/home/daniel/.local/lib/python2.7/site-packages/pandas/core/internals/blocks.py", line 534, in astype
>     **kwargs)
>   File "/home/daniel/.local/lib/python2.7/site-packages/pandas/core/internals/blocks.py", line 595, in _astype
>     dtype = pandas_dtype(dtype)
>   File "/home/daniel/.local/lib/python2.7/site-packages/pandas/core/dtypes/common.py", line 2029, in pandas_dtype
>     raise TypeError("dtype '{}' not understood".format(dtype))
> TypeError: dtype '<class 'future.types.newint.newint'>' not understood

**Comment by sr-murthy** [comment]
@DanielTrisura The Pandas error is known to us - it has been fixed as part of the upcoming release, which will be either tomorrow or Monday. I assume you're using the existing release to run against PiWind `master` - it is an error which only occurs when using Python 2.7.x, not Python 3. So a short term solution that would work for you is to use Python 3.

**Comment by DanielTrisura** [comment]
Thank you for the speedy response, I think I’ll wait till the update occurs so that I can more closely document my installation process for others in the office.

Thank you again,

Daniel Figueroa
Actuarial Analyst
Trisura Specialty Insurance Company
210 Park Avenue, Suite 1400
Oklahoma City, OK  73102-5636
405.594.4960  Main
405.309.8647  Direct
405.667.3158  Mobile
405.594.4969  Fax
[EPS TrisuraLogo_BoxHorizontal_PMS370]

**Comment by sr-murthy** [comment]
This was the fix in the MDK

https://github.com/OasisLMF/OasisLMF/issues/188

which will end up in the next release

**Comment by hsteptoe** [comment]
The original problem at the top of this thread is not fixed (as of today).  This was specifically to do with your Binder build, which still fails because it can't find `source_exposure_file_path`, rather than the `pandas` issue noted by @DanielTrisura which seems to have hijacked my original issue.

**Comment by sr-murthy** [comment]
@hsteptoe It's not really the Binder image of PiWind that is the problem here - it's because the MDK config. file in PiWind `master` is now inconsistent with the way that the key names that the `model run` command in the latest MDK release expects - so in the release version `model run` expects a key named `source_exposure_file_path`, not `source_exposures_file_path`, etc.

PiWind `develop` is now consistent with the latest MDK release, so this will have to be merged into `master` - @sambles I think it should be fine to do this merge now. @hsteptoe But you can try running the notebook in PiWind `develop`, if possible.

**Comment by sambles** [comment]
Note: Issue fixed after PiWind cleanup, however the link needed updating (working now)
