### ISSUE TITLE
Warnings raised during installation

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisPiWind#41]
When pip installing the requirements the following warnings are reported. The MDK commands still run.

oasislmf 1.3.3 has requirement pandas>=0.24.0, but you'll have pandas 0.22.0 which is incompatible.
oasislmf 1.3.3 has requirement requests>=2.20.0, but you'll have requests 2.18.4 which is incompatible.
oasislmf 1.3.3 has requirement shapely>=1.6.4.post1, but you'll have shapely 1.5.13 which is incompatible.

**Comment by sr-murthy** [comment]
Is this in a virtual env.? The MDK installation in a virtual env. is guaranteed to result in an overwriting of any pre-existing packages installed in the environment with the same packages in the installation but with versions defined in the MDK requirements file (`requirements.txt`). So if you had Pandas `0.22.0` installed in your virtual env. prior to an MDK install installing it now should overwrite that version with the `0.24.1`, which is the Pandas version defined in the MDK requirements file.

That warning will only occur if you're trying to install an older version of a package defined in the MDK requirements.

**Comment by sr-murthy** [comment]
Is this in a virtual env.? The MDK installation in a virtual env. is guaranteed to result in an overwriting of any pre-existing packages installed in the environment with the same packages in the installation but with versions defined in the MDK requirements file (`requirements.txt`). So if you had Pandas `0.22.0` installed in your virtual env. prior to an MDK install, then installing the MDK should overwrite that version with the `0.24.1`, which is the Pandas version defined in the MDK requirements file.

That warning will only occur if you're trying to install an older version of a package defined in the MDK requirements.

**Comment by mpinkerton-oasis** [comment]
It's in a completely fresh MDK version. Different versions for these packages are explicitly set in the repo requirements file which is causing the issue. Would it be better to switch over to using pip-tools to manage this better?

**Comment by sr-murthy** [comment]
There are not different versions of Pandas defined in the MDK requirements - there is a single `requirements.txt` file that we update any time that the requirements source/input files (`requirements.in`, `requirements-package.in`) change. And yes, we already use `pip-tools` to manage this process.

Note that the `requirements.in` and `requirements-package.in` are source requirements files which represent the list of packages required for the tests + package framework and for the core MDK functionality respectively, and if any changes to these made by the developer will require the developer to run `pip-compile` to build a new `requirements.txt` file from those source files.

**Comment by mpinkerton-oasis** [comment]
This issue relates to the OasisPiWind requirements, not the MDK standalone requirements.

**Comment by sr-murthy** [comment]
Well, PiWind is a model repository, separate from the MDK, and it does appear to define some older versions of packages also used by the MDK. SO if you install these via PiWind after installing the MDK then you will get those warnings. But they are warnings, not errors, so this issue is not about any errors.

The solution is to update the PiWind requirements, but frankly as PiWind uses a MDK built-in lookup framework, and doesn't contain any kind of custom code any more, there is no need to have any requirements files.

**Comment by sr-murthy** [comment]
Requirements updated to remove packages installed by the MDK
