### ISSUE TITLE
Multi-peril multi-coverage numerical testing for Oasis platform control results set

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisPiWind#48]
Ben to triage

**Comment by KamalCharles** [comment]
Hi Joh,
What is it you need exatcly? A set of input files?

**Comment by johcarter** [comment]
A set of output files
for the tests in OasisPiWind/tests/conf.ini
please @KamalCharles . are you around to discuss on monday?

**Comment by johcarter** [comment]
gul and il results are correct in develop branch $ oasislmf model run -C oasislmf.json. ri results are incorrect due to https://github.com/OasisLMF/OasisLMF/issues/415

**Comment by johcarter** [comment]
fixed in branch fix/file-generation-cleanup
fyi @sambles

**Comment by johcarter** [comment]
@KamalCharles @sambles the piwind model_data/ and tests/ and config oasislmf.json in merge-kam dev are ready to be pulled into develop please. This is the multi-peril piwind model.

@sambles the new expected results control data for the build test is in this branch in tests/expected/control_data/. I have a correction to make to the lec reports but otherwise the numbers in the reports are correct for this model.

thanks both

**Comment by sambles** [comment]
Merged in PR #54
