### ISSUE TITLE
Cannot clone submodules.

### ISSUE THREAD

**Issue by cdlhub** [OasisLMF/OasisPiWind#7]
PiWind [README](https://github.com/OasisLMF/OasisPiWind/blob/master/README.md) is specifying `--recursive` in order to clone the repository. However, submodules are not accessible. Is there a plan to open source them in a near future? Thank you.

```
$ git clone --recursive git@github.com:OasisLMF/OasisPiWind.git
Cloning into 'OasisPiWind'...
...
Submodule 'oasis_build_utils' (git+ssh://git@github.com/OasisLMF/oasis_build_utils) registered for path 'oasis_build_utils'
...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
...
Failed to clone 'oasis_build_utils' a second time, aborting
```

**Comment by sr-murthy** [comment]
@cdlhub PiWind uses three private Oasis repositories as submodules but users who have been given read access to them are able to clone PiWind.

I think this open sourcing is under discussion but please refer to @mpinkerton-oasis.

**Comment by cdlhub** [comment]
Thank you.
